/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process serves HTTP. Never touches dependencies. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: database, Meilisearch and object storage are reachable. */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        CheckStatus: "ok" | "fail";
        Checks: {
            database: components["schemas"]["CheckStatus"];
            meilisearch: components["schemas"]["CheckStatus"];
            storage: components["schemas"]["CheckStatus"];
        };
        Health: {
            status: components["schemas"]["CheckStatus"];
        };
        /** @description RFC 9457 problem details body. */
        Problem: {
            /** @description Stable machine-readable error code, e.g. `not_found`. */
            code: string;
            detail?: string | null;
            /** Format: int32 */
            status: number;
            title: string;
            /** @description Always `about:blank`; `code` carries the specific error kind. */
            type: string;
        };
        Readiness: {
            checks: components["schemas"]["Checks"];
            /**
             * @description `ok` when the core dependencies (database, storage) are `ok`. Meilisearch is reported
             *     but not required: search degrades, the shop keeps working (spec A30).
             */
            status: components["schemas"]["CheckStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
