//! Helper proposals (§12.2): product/category descriptions, SEO title + meta and translations.
//! A proposal is generated by a job (`ai.proposal`), shown to the staff as before/after per
//! field, and nothing is written until the staff accepts fields; accepted fields go through
//! the entity's service and get an AI marker.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::sync::{Arc, LazyLock, Mutex};

use chrono::{DateTime, Utc};
use platform::Error;
use platform::db::{TenantTx, tenant_tx};
use platform::queue::{self, NewJob};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use sqlx::PgPool;
use utoipa::ToSchema;
use uuid::Uuid;

use super::fields::{Doc, EntityType};
use super::glossary::{self, Glossary};
use super::{Ai, Call, CallError, Outcome, marks, prompts};
use crate::audit;
use crate::catalog::I18n;
use crate::markets::is_locale;

pub const JOB: &str = "ai.proposal";
pub const MAX_TARGETS: usize = 5;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ProposalKind {
    ProductDescription,
    Seo,
    CategoryDescription,
    Translate,
}

impl ProposalKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ProductDescription => super::PRODUCT_DESCRIPTION,
            Self::Seo => super::SEO,
            Self::CategoryDescription => super::CATEGORY_DESCRIPTION,
            Self::Translate => super::TRANSLATE,
        }
    }

    fn parse(s: &str) -> Self {
        match s {
            "product_description" => Self::ProductDescription,
            "seo" => Self::Seo,
            "category_description" => Self::CategoryDescription,
            _ => Self::Translate,
        }
    }

    fn allows(self, t: EntityType) -> bool {
        match self {
            Self::ProductDescription => t == EntityType::Product,
            Self::CategoryDescription => t == EntityType::Category,
            Self::Seo => t != EntityType::Menu,
            Self::Translate => true,
        }
    }
}

/// Voice of generated descriptions.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Tone {
    #[default]
    Neutral,
    Friendly,
    Premium,
    Technical,
    Playful,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Length {
    Short,
    #[default]
    Medium,
    Long,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct NewProposal {
    pub kind: ProposalKind,
    pub entity_type: EntityType,
    /// The entity's id (a menu's handle).
    pub entity_id: String,
    /// Language of the text to write; the source language for `translate`.
    #[schema(example = "cs")]
    pub locale: String,
    /// `translate` only: 1-5 languages to translate into.
    #[serde(default)]
    pub target_locales: Vec<String>,
    /// Descriptions only.
    #[serde(default)]
    pub tone: Tone,
    /// Descriptions only.
    #[serde(default)]
    pub length: Length,
}

fn invalid(code: &'static str, detail: impl Into<String>) -> Error {
    Error::Validation {
        code,
        detail: detail.into(),
    }
}

impl NewProposal {
    pub fn validate(&self) -> Result<(), Error> {
        if !self.kind.allows(self.entity_type) {
            return Err(invalid(
                "invalid_proposal",
                format!(
                    "{} cannot be generated for a {}",
                    self.kind.as_str(),
                    self.entity_type.as_str()
                ),
            ));
        }
        if !(1..=64).contains(&self.entity_id.len()) {
            return Err(Error::NotFound);
        }
        if !is_locale(&self.locale) {
            return Err(invalid("invalid_locale", "locale must be like cs or en-GB"));
        }
        let targets: BTreeSet<&str> = self.target_locales.iter().map(String::as_str).collect();
        if self.kind == ProposalKind::Translate {
            if targets.is_empty()
                || targets.len() > MAX_TARGETS
                || targets.len() != self.target_locales.len()
                || targets.contains(self.locale.as_str())
                || !targets.iter().all(|l| is_locale(l))
            {
                return Err(invalid(
                    "invalid_locale",
                    format!(
                        "target_locales: 1-{MAX_TARGETS} distinct locales other than the source"
                    ),
                ));
            }
        } else if !targets.is_empty() {
            return Err(invalid(
                "invalid_proposal",
                "target_locales is for translations only",
            ));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ProposalStatus {
    /// Being generated (a job).
    Pending,
    /// Waiting for the staff's decision.
    Ready,
    Failed,
    Accepted,
    Discarded,
}

impl ProposalStatus {
    fn parse(s: &str) -> Self {
        match s {
            "ready" => Self::Ready,
            "failed" => Self::Failed,
            "accepted" => Self::Accepted,
            "discarded" => Self::Discarded,
            _ => Self::Pending,
        }
    }
}

/// One proposed field value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct Change {
    pub locale: String,
    /// `name`, `description_html`, `seo_title`, ... (`blocks` for a page's blocks, `labels`
    /// for a menu's labels: `[{path, label}]`).
    pub field: String,
    /// The value when the proposal was generated (`null`: none yet).
    pub before: Option<Value>,
    /// The proposed value: text, or the block/label list.
    pub after: Value,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Progress {
    pub done: i64,
    pub total: i64,
}

#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct Proposal {
    pub id: Uuid,
    pub kind: ProposalKind,
    pub entity_type: EntityType,
    pub entity_id: String,
    pub locale: String,
    pub target_locales: Vec<String>,
    pub tone: Tone,
    pub length: Length,
    pub status: ProposalStatus,
    pub progress: Progress,
    pub changes: Vec<Change>,
    /// Things to check before accepting (e.g. a glossary term not kept).
    pub warnings: Vec<String>,
    /// Failure code: `ai_quota_exceeded`, `ai_unavailable`, `ai_refused`,
    /// `ai_invalid_output`, `entity_missing`, `nothing_to_translate`.
    pub error: Option<String>,
    /// The model that wrote it (`fake` for the demo provider).
    pub model: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct FieldRef {
    pub locale: String,
    pub field: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct AcceptProposal {
    /// The fields to write (a subset of `changes`). Creating a translation always includes
    /// its name/title and slug.
    pub fields: Vec<FieldRef>,
}

fn internal(e: serde_json::Error) -> Error {
    Error::Internal(e.to_string())
}

// ---------------------------------------------------------------------------------------
// Create, read, accept, discard

/// Starts a proposal (`402 ai_quota_exceeded` when the allowance is used up): stores it as
/// `pending` and queues the generation job.
pub async fn create(
    tx: &mut TenantTx,
    ai: &Ai,
    actor: &str,
    input: &NewProposal,
) -> Result<Proposal, Error> {
    input.validate()?;
    super::ensure_quota(tx, ai).await?;
    let doc = Doc::load(tx, input.entity_type, &input.entity_id).await?;
    if !doc.has_locale(&input.locale) {
        return Err(invalid(
            "translation_missing",
            format!(
                "the {} has no content in {}",
                input.entity_type.as_str(),
                input.locale
            ),
        ));
    }
    let id = crate::id::new_id();
    let total = match input.kind {
        ProposalKind::Translate => input.target_locales.len(),
        _ => 1,
    };
    sqlx::query!(
        "INSERT INTO ai_proposals (id, tenant_id, kind, entity_type, entity_id, params, progress,
                                   created_by)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)",
        id,
        tx.tenant_id(),
        input.kind.as_str(),
        input.entity_type.as_str(),
        input.entity_id,
        serde_json::to_value(input).map_err(internal)?,
        json!({ "done": 0, "total": total }),
        actor
    )
    .execute(&mut **tx)
    .await?;
    let mut job = NewJob::new(JOB, json!({ "proposal_id": id }));
    job.tenant_id = Some(tx.tenant_id());
    job.max_attempts = 3;
    job.idempotency_key = Some(format!("{JOB}:{id}"));
    queue::enqueue(&mut **tx, &job).await?;
    get(tx, id).await
}

pub async fn get(tx: &mut TenantTx, id: Uuid) -> Result<Proposal, Error> {
    let r = sqlx::query!(
        "SELECT id, kind, entity_type, entity_id, params, status, progress, changes, warnings,
                error, model, created_at, updated_at
         FROM ai_proposals WHERE id = $1",
        id
    )
    .fetch_optional(&mut **tx)
    .await?
    .ok_or(Error::NotFound)?;
    let params: NewProposal = serde_json::from_value(r.params).map_err(internal)?;
    Ok(Proposal {
        id: r.id,
        kind: ProposalKind::parse(&r.kind),
        entity_type: EntityType::parse(&r.entity_type).ok_or(Error::NotFound)?,
        entity_id: r.entity_id,
        locale: params.locale,
        target_locales: params.target_locales,
        tone: params.tone,
        length: params.length,
        status: ProposalStatus::parse(&r.status),
        progress: serde_json::from_value(r.progress).unwrap_or_default(),
        changes: serde_json::from_value(r.changes).map_err(internal)?,
        warnings: serde_json::from_value(r.warnings).map_err(internal)?,
        error: r.error,
        model: r.model,
        created_at: r.created_at,
        updated_at: r.updated_at,
    })
}

/// Writes the chosen fields through the entity's service (audited), marks them as AI-written
/// and closes the proposal. `409 proposal_stale` when a field changed since generation.
pub async fn accept(
    tx: &mut TenantTx,
    actor: &str,
    id: Uuid,
    input: &AcceptProposal,
) -> Result<Proposal, Error> {
    let status = sqlx::query_scalar!(
        "SELECT status FROM ai_proposals WHERE id = $1 FOR UPDATE",
        id
    )
    .fetch_optional(&mut **tx)
    .await?
    .ok_or(Error::NotFound)?;
    if status != "ready" {
        return Err(Error::Conflict {
            code: "proposal_not_ready",
            detail: format!("the proposal is {status}"),
        });
    }
    let proposal = get(tx, id).await?;
    if input.fields.is_empty() || input.fields.len() > proposal.changes.len() {
        return Err(invalid("no_fields", "choose at least one proposed field"));
    }
    Doc::lock(tx, proposal.entity_type, &proposal.entity_id).await?;
    let mut doc = Doc::load(tx, proposal.entity_type, &proposal.entity_id).await?;
    let find = |locale: &str, field: &str| {
        proposal
            .changes
            .iter()
            .find(|c| c.locale == locale && c.field == field)
    };
    let mut chosen: Vec<&Change> = vec![];
    for f in &input.fields {
        let c = find(&f.locale, &f.field).ok_or_else(|| {
            invalid(
                "unknown_field",
                format!("{} ({}) is not in the proposal", f.field, f.locale),
            )
        })?;
        if !chosen.contains(&c) {
            chosen.push(c);
        }
    }
    // A new translation needs its name/title and slug.
    let new_locales: BTreeSet<String> = chosen
        .iter()
        .filter(|c| !doc.has_locale(&c.locale))
        .map(|c| c.locale.clone())
        .collect();
    if let Some(title) = proposal.entity_type.title_field() {
        for locale in &new_locales {
            for field in [title, "slug"] {
                if let Some(c) = find(locale, field)
                    && !chosen.contains(&c)
                {
                    chosen.push(c);
                }
            }
        }
    }
    for c in &chosen {
        if doc.get(&c.locale, &c.field) != c.before {
            return Err(Error::Conflict {
                code: "proposal_stale",
                detail: format!(
                    "{} ({}) changed after the proposal was made; generate a new one",
                    c.field, c.locale
                ),
            });
        }
    }
    for c in &chosen {
        doc.set(&c.locale, &c.field, &c.after)?;
    }
    let saved = doc.save(tx, actor).await?;
    let model = proposal.model.clone().unwrap_or_default();
    for c in chosen.iter().filter(|c| c.field != "slug") {
        if let Some(value) = saved.get(&c.locale, &c.field) {
            marks::record(
                tx,
                proposal.entity_type,
                &proposal.entity_id,
                &marks::NewMark {
                    locale: &c.locale,
                    field: &c.field,
                    value: &value,
                    feature: proposal.kind.as_str(),
                    model: &model,
                    proposal_id: id,
                    accepted_by: actor,
                },
            )
            .await?;
        }
    }
    sqlx::query!(
        "UPDATE ai_proposals SET status = 'accepted', updated_at = now() WHERE id = $1",
        id
    )
    .execute(&mut **tx)
    .await?;
    let fields: Vec<Value> = chosen
        .iter()
        .map(|c| json!({ "locale": c.locale, "field": c.field }))
        .collect();
    audit::record(
        tx,
        actor,
        "ai.proposal.accepted",
        "ai_proposal",
        Some(&id.to_string()),
        &json!({
            "kind": proposal.kind,
            "entity_type": proposal.entity_type,
            "entity_id": proposal.entity_id,
            "model": proposal.model,
            "fields": fields,
        }),
    )
    .await?;
    get(tx, id).await
}

pub async fn discard(tx: &mut TenantTx, id: Uuid) -> Result<Proposal, Error> {
    let done = sqlx::query!(
        "UPDATE ai_proposals SET status = 'discarded', updated_at = now()
         WHERE id = $1 AND status IN ('pending', 'ready', 'failed')",
        id
    )
    .execute(&mut **tx)
    .await?;
    if done.rows_affected() == 0 {
        get(tx, id).await?;
        return Err(Error::Conflict {
            code: "proposal_not_ready",
            detail: "the proposal is already closed".into(),
        });
    }
    get(tx, id).await
}

// ---------------------------------------------------------------------------------------
// Generation (the job)

/// Generates a pending proposal. Permanent failures are stored on the proposal; transient ones
/// ask for a retry until `last_attempt`.
pub async fn run(
    db: &PgPool,
    ai: &Ai,
    tenant: Uuid,
    id: Uuid,
    last_attempt: bool,
) -> Result<Outcome, Error> {
    let (proposal, actor, doc) = {
        let mut tx = tenant_tx(db, tenant).await?;
        let proposal = get(&mut tx, id).await?;
        if proposal.status != ProposalStatus::Pending {
            return Ok(Outcome::Done);
        }
        let actor = sqlx::query_scalar!("SELECT created_by FROM ai_proposals WHERE id = $1", id)
            .fetch_one(&mut *tx)
            .await?;
        let doc = match Doc::load(&mut tx, proposal.entity_type, &proposal.entity_id).await {
            Ok(d) => Some(d),
            Err(Error::NotFound) => None,
            Err(e) => return Err(e),
        };
        tx.commit().await?;
        (proposal, actor, doc)
    };
    let Some(doc) = doc else {
        fail(db, tenant, id, "entity_missing").await?;
        return Ok(Outcome::Done);
    };
    let g = Gen {
        db,
        ai,
        tenant,
        actor: &actor,
        p: &proposal,
        doc: &doc,
    };
    let result = match proposal.kind {
        ProposalKind::ProductDescription => g.product_description().await,
        ProposalKind::CategoryDescription => g.category_description().await,
        ProposalKind::Seo => g.seo().await,
        ProposalKind::Translate => g.translate(id).await,
    };
    match result {
        Ok((changes, warnings, model)) => {
            let mut tx = tenant_tx(db, tenant).await?;
            sqlx::query!(
                "UPDATE ai_proposals SET status = 'ready', changes = $2, warnings = $3, model = $4,
                        progress = jsonb_set(progress, '{done}', progress->'total'),
                        updated_at = now()
                 WHERE id = $1 AND status = 'pending'",
                id,
                serde_json::to_value(&changes).map_err(internal)?,
                json!(warnings),
                model
            )
            .execute(&mut *tx)
            .await?;
            tx.commit().await?;
            Ok(Outcome::Done)
        }
        Err(e) if e.retryable() && !last_attempt => Ok(Outcome::Retry(e.to_string())),
        Err(e) => {
            tracing::warn!(proposal = %id, code = e.code(), error = %e, "ai proposal failed");
            fail(db, tenant, id, e.code()).await?;
            Ok(Outcome::Done)
        }
    }
}

async fn fail(db: &PgPool, tenant: Uuid, id: Uuid, code: &str) -> Result<(), Error> {
    let mut tx = tenant_tx(db, tenant).await?;
    sqlx::query!(
        "UPDATE ai_proposals SET status = 'failed', error = $2, updated_at = now()
         WHERE id = $1 AND status = 'pending'",
        id,
        code
    )
    .execute(&mut *tx)
    .await?;
    tx.commit().await?;
    Ok(())
}

type Generated = (Vec<Change>, Vec<String>, String);

struct Gen<'a> {
    db: &'a PgPool,
    ai: &'a Ai,
    tenant: Uuid,
    actor: &'a str,
    p: &'a Proposal,
    doc: &'a Doc,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct DescriptionOut {
    description_html: String,
    short_description: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CategoryDescriptionOut {
    description_html: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct SeoOut {
    seo_title: String,
    seo_description: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TranslationOut {
    fields: Vec<TranslatedField>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TranslatedField {
    key: String,
    text: String,
}

/// Generated descriptions: text structure only (no links, images or attributes).
static STRICT: LazyLock<ammonia::Builder<'static>> = LazyLock::new(|| {
    let mut b = ammonia::Builder::empty();
    b.add_tags(["p", "ul", "ol", "li", "strong", "em", "h3", "h4", "br"])
        .clean_content_tags(["script", "style"].into_iter().collect());
    b
});

pub fn sanitize_generated(html: &str) -> String {
    STRICT.clean(html).to_string()
}

/// URLs (`href`/`src`) of sanitized HTML.
fn urls(html: &str) -> HashSet<String> {
    let found = Arc::new(Mutex::new(HashSet::new()));
    let sink = found.clone();
    ammonia::Builder::default()
        .attribute_filter(move |_, attr, value| {
            if matches!(attr, "href" | "src")
                && let Ok(mut set) = sink.lock()
            {
                set.insert(value.to_owned());
            }
            Some(value.into())
        })
        .clean(html);
    found.lock().map(|s| s.clone()).unwrap_or_default()
}

/// Translated HTML: the usual sanitizing, and links/images only to URLs of the source.
pub fn sanitize_translated(html: &str, source: &str) -> String {
    let allowed = urls(source);
    let clean = crate::catalog::sanitize_html(html);
    ammonia::Builder::default()
        .url_schemes(["http", "https", "mailto", "tel"].into_iter().collect())
        .attribute_filter(move |_, attr, value| {
            if matches!(attr, "href" | "src") && !allowed.contains(value) {
                None
            } else {
                Some(value.into())
            }
        })
        .clean(&clean)
        .to_string()
}

/// Cuts `s` to at most `max` characters.
fn clip(s: &str, max: usize) -> String {
    s.trim()
        .chars()
        .take(max)
        .collect::<String>()
        .trim()
        .to_owned()
}

fn plain(html: &str, max: usize) -> String {
    crate::storefront::plain_excerpt(html, max)
}

fn i18n_get(m: &I18n, locale: &str) -> Option<String> {
    m.get(locale).or_else(|| m.values().next()).cloned()
}

/// Longest allowed value per field (the services' limits).
fn max_len(field: &str) -> usize {
    match field {
        "name" => 300,
        "title" | "seo_title" => 200,
        "seo_description" | "excerpt" => 500,
        "short_description" => 1000,
        "label" => 100,
        _ => crate::catalog::MAX_HTML,
    }
}

impl Gen<'_> {
    async fn call(
        &self,
        feature: &'static str,
        task: &str,
        data: &Value,
        schema: &Value,
    ) -> Result<(Value, String), CallError> {
        super::call(
            self.db,
            self.ai,
            self.tenant,
            self.actor,
            &Call {
                feature,
                system: prompts::HELPER_SYSTEM,
                task,
                data,
                schema,
                max_tokens: 8000,
            },
        )
        .await
    }

    fn text(&self, field: &str) -> String {
        self.doc
            .get(&self.p.locale, field)
            .and_then(|v| v.as_str().map(str::to_owned))
            .unwrap_or_default()
    }

    fn change(&self, field: &str, after: String) -> Result<Change, CallError> {
        if after.trim().is_empty() {
            return Err(CallError::output(format!("{field} is empty")));
        }
        Ok(Change {
            locale: self.p.locale.clone(),
            field: field.into(),
            before: self.doc.get(&self.p.locale, field),
            after: json!(after),
        })
    }

    async fn product_description(&self) -> Result<Generated, CallError> {
        let Doc::Product(p) = self.doc else {
            return Err(CallError::output("not a product"));
        };
        let locale = self.p.locale.as_str();
        let mut tx = tenant_tx(self.db, self.tenant).await?;
        let ids: Vec<Uuid> = p.parameters.iter().map(|v| v.parameter_id).collect();
        let defs: BTreeMap<Uuid, (I18n, Option<String>)> = sqlx::query!(
            "SELECT id, name_i18n, unit FROM parameters WHERE id = ANY($1)",
            &ids
        )
        .fetch_all(&mut *tx)
        .await?
        .into_iter()
        .map(|r| {
            (
                r.id,
                (
                    serde_json::from_value(r.name_i18n).unwrap_or_default(),
                    r.unit,
                ),
            )
        })
        .collect();
        let categories = sqlx::query_scalar!(
            "SELECT name FROM category_translations WHERE category_id = ANY($1) AND locale = $2",
            &p.category_ids,
            locale
        )
        .fetch_all(&mut *tx)
        .await?;
        tx.commit().await?;
        let parameters: Vec<Value> = p
            .parameters
            .iter()
            .filter(|v| v.variant_sku.is_none())
            .filter_map(|v| {
                let (names, unit) = defs.get(&v.parameter_id)?;
                let value = match &v.value {
                    Value::Object(m) => m
                        .get(locale)
                        .or_else(|| m.values().next())?
                        .as_str()?
                        .to_owned(),
                    Value::Number(n) => match unit {
                        Some(u) => format!("{n} {u}"),
                        None => n.to_string(),
                    },
                    Value::Bool(b) => if *b { "yes" } else { "no" }.to_owned(),
                    _ => return None,
                };
                Some(json!({ "name": i18n_get(names, locale)?, "value": value }))
            })
            .collect();
        let options: Vec<Value> = p
            .options
            .iter()
            .map(|o| {
                json!({
                    "name": i18n_get(&o.name_i18n, locale),
                    "values": o.values.iter().filter_map(|v| i18n_get(&v.name_i18n, locale)).collect::<Vec<_>>(),
                })
            })
            .collect();
        let data = json!({
            "locale": locale,
            "tone": self.p.tone,
            "length": self.p.length,
            "product": {
                "name": self.text("name"),
                "brand": p.brand,
                "categories": categories,
                "existing_description_html": self.text("description_html"),
                "short_description": self.text("short_description"),
                "parameters": parameters,
                "options": options,
                "safety_info": p.gpsr.safety_info.get(locale),
                "warnings": p.gpsr.warnings.get(locale),
            },
        });
        let task = format!(
            "Write the product description in language `{locale}` with tone `{:?}` and length `{:?}` (lowercase preset names). Return description_html and short_description.",
            self.p.tone, self.p.length
        );
        let (out, model) = self
            .call(
                super::PRODUCT_DESCRIPTION,
                &task,
                &data,
                &prompts::description_schema(),
            )
            .await?;
        let out: DescriptionOut = super::parse(out)?;
        let changes = vec![
            self.change(
                "description_html",
                clip(
                    &sanitize_generated(&out.description_html),
                    max_len("description_html"),
                ),
            )?,
            self.change(
                "short_description",
                clip(
                    &plain(&out.short_description, 1000),
                    max_len("short_description"),
                ),
            )?,
        ];
        Ok((changes, vec![], model))
    }

    async fn category_description(&self) -> Result<Generated, CallError> {
        let Doc::Category(c) = self.doc else {
            return Err(CallError::output("not a category"));
        };
        let locale = self.p.locale.as_str();
        let mut tx = tenant_tx(self.db, self.tenant).await?;
        let parent =
            match c.parent_id {
                None => None,
                Some(parent) => sqlx::query_scalar!(
                    "SELECT name FROM category_translations WHERE category_id = $1 AND locale = $2",
                    parent,
                    locale
                )
                .fetch_optional(&mut *tx)
                .await?,
            };
        let products = sqlx::query_scalar!(
            "SELECT t.name FROM product_categories pc
             JOIN product_translations t ON t.product_id = pc.product_id AND t.locale = $2
             WHERE pc.category_id = $1 ORDER BY pc.position LIMIT 20",
            c.id,
            locale
        )
        .fetch_all(&mut *tx)
        .await?;
        tx.commit().await?;
        let data = json!({
            "locale": locale,
            "tone": self.p.tone,
            "length": self.p.length,
            "category": {
                "name": self.text("name"),
                "parent": parent,
                "existing_description_html": self.text("description_html"),
                "products": products,
            },
        });
        let task = format!(
            "Write the category description in language `{locale}` with tone `{:?}` and length `{:?}` (lowercase preset names). Return description_html.",
            self.p.tone, self.p.length
        );
        let (out, model) = self
            .call(
                super::CATEGORY_DESCRIPTION,
                &task,
                &data,
                &prompts::category_description_schema(),
            )
            .await?;
        let out: CategoryDescriptionOut = super::parse(out)?;
        let changes = vec![self.change(
            "description_html",
            clip(
                &sanitize_generated(&out.description_html),
                max_len("description_html"),
            ),
        )?];
        Ok((changes, vec![], model))
    }

    async fn seo(&self) -> Result<Generated, CallError> {
        let (name, brand, text) = match self.doc {
            Doc::Product(p) => (
                self.text("name"),
                p.brand.clone(),
                format!(
                    "{} {}",
                    self.text("short_description"),
                    plain(&self.text("description_html"), 3000)
                ),
            ),
            Doc::Category(_) => (
                self.text("name"),
                None,
                plain(&self.text("description_html"), 3000),
            ),
            Doc::Page(p) => {
                let blocks = p
                    .translations
                    .iter()
                    .find(|t| t.locale == self.p.locale)
                    .map(|t| crate::content::blocks::plain_text(&t.blocks))
                    .unwrap_or_default();
                (
                    self.text("title"),
                    None,
                    format!("{} {}", self.text("excerpt"), clip(&blocks, 3000)),
                )
            }
            Doc::Menu { .. } => return Err(CallError::output("menus have no SEO fields")),
        };
        let locale = &self.p.locale;
        let data = json!({
            "locale": locale,
            "entity_type": self.p.entity_type,
            "name": name,
            "brand": brand,
            "text": text.trim(),
        });
        let task = format!(
            "Write the SEO title and meta description in language `{locale}` for this {}.",
            self.p.entity_type.as_str()
        );
        let (out, model) = self
            .call(super::SEO, &task, &data, &prompts::seo_schema())
            .await?;
        let out: SeoOut = super::parse(out)?;
        let changes = vec![
            self.change(
                "seo_title",
                clip(&plain(&out.seo_title, 500), max_len("seo_title")),
            )?,
            self.change(
                "seo_description",
                clip(
                    &plain(&out.seo_description, 1000),
                    max_len("seo_description"),
                ),
            )?,
        ];
        Ok((changes, vec![], model))
    }

    async fn translate(&self, id: Uuid) -> Result<Generated, CallError> {
        let source = self.p.locale.as_str();
        let units = units(self.doc, source);
        if units.is_empty() {
            return Err(CallError::Failed {
                code: "nothing_to_translate",
                detail: "the source has no text".into(),
            });
        }
        let glossary = {
            let mut tx = tenant_tx(self.db, self.tenant).await?;
            let g = glossary::get(&mut tx).await?;
            tx.commit().await?;
            g
        };
        let all_source: String = units.iter().map(Unit::plain).collect::<Vec<_>>().join("\n");
        let mut changes = vec![];
        let mut warnings = vec![];
        let mut model = String::new();
        for (i, target) in self.p.target_locales.iter().enumerate() {
            let (out, used) = self
                .translate_one(&units, &glossary, &all_source, target)
                .await?;
            model = used;
            let (mut c, mut w) = self.assemble(&units, &glossary, target, &out)?;
            changes.append(&mut c);
            warnings.append(&mut w);
            let mut tx = tenant_tx(self.db, self.tenant).await?;
            sqlx::query!(
                "UPDATE ai_proposals SET progress = jsonb_build_object('done', $2::bigint, 'total', progress->'total'),
                        updated_at = now()
                 WHERE id = $1",
                id,
                i64::try_from(i + 1).unwrap_or(i64::MAX)
            )
            .execute(&mut *tx)
            .await?;
            tx.commit().await?;
        }
        Ok((changes, warnings, model))
    }

    async fn translate_one(
        &self,
        units: &[Unit],
        glossary: &Glossary,
        all_source: &str,
        target: &str,
    ) -> Result<(BTreeMap<String, String>, String), CallError> {
        let terms: Vec<Value> = glossary
            .applicable(all_source, target)
            .into_iter()
            .map(|(term, form)| json!({ "term": term, "use": form }))
            .collect();
        let data = json!({
            "source_locale": self.p.locale,
            "target_locale": target,
            "glossary": terms,
            "fields": units.iter().map(|u| json!({ "key": u.key, "text": u.text, "html": u.html })).collect::<Vec<_>>(),
        });
        let task = format!(
            "Translate every field from `{}` into `{target}`. Keep glossary terms in their given form. Return all {} field keys.",
            self.p.locale,
            units.len()
        );
        let (out, model) = self
            .call(
                super::TRANSLATE,
                &task,
                &data,
                &prompts::translation_schema(),
            )
            .await?;
        let out: TranslationOut = super::parse(out)?;
        let mut map = BTreeMap::new();
        for f in out.fields {
            if map.insert(f.key.clone(), f.text).is_some() {
                return Err(CallError::output(format!("field {} returned twice", f.key)));
            }
        }
        let expected: BTreeSet<&str> = units.iter().map(|u| u.key.as_str()).collect();
        let got: BTreeSet<&str> = map.keys().map(String::as_str).collect();
        if expected != got {
            return Err(CallError::output(
                "the translation does not return exactly the requested fields",
            ));
        }
        Ok((map, model))
    }

    /// Turns translated units into changes for `target`, plus glossary warnings.
    fn assemble(
        &self,
        units: &[Unit],
        glossary: &Glossary,
        target: &str,
        out: &BTreeMap<String, String>,
    ) -> Result<(Vec<Change>, Vec<String>), CallError> {
        let mut changes = vec![];
        let mut warnings = vec![];
        let mut blocks = None::<Value>;
        let mut labels = vec![];
        for u in units {
            let raw = out.get(&u.key).map(String::as_str).unwrap_or_default();
            let leaf = if u.key.starts_with("labels.") {
                "label"
            } else {
                u.key.rsplit('.').next().unwrap_or(&u.key)
            };
            let text = if u.html {
                clip(
                    &sanitize_translated(raw, &u.text),
                    max_len("description_html"),
                )
            } else {
                clip(&plain(raw, 5000), max_len(leaf))
            };
            if text.is_empty() {
                return Err(CallError::output(format!("{} is empty", u.key)));
            }
            let output = if u.html {
                plain(&text, usize::MAX)
            } else {
                text.clone()
            };
            for term in glossary.violations(&u.plain(), &output, target) {
                warnings.push(format!(
                    "{target}: {}: glossary term \"{term}\" was not kept",
                    u.key
                ));
            }
            if let Some(rest) = u.key.strip_prefix("blocks.") {
                let b = blocks.get_or_insert_with(|| {
                    self.doc
                        .get(&self.p.locale, "blocks")
                        .unwrap_or(Value::Null)
                });
                let pointer = format!("/{}", rest.replace('.', "/"));
                if let Some(slot) = b.pointer_mut(&pointer) {
                    *slot = json!(text);
                }
            } else if let Some(path) = u.key.strip_prefix("labels.") {
                labels.push(json!({ "path": path, "label": text }));
            } else {
                changes.push(Change {
                    locale: target.into(),
                    field: u.key.clone(),
                    before: self.doc.get(target, &u.key),
                    after: json!(text),
                });
            }
        }
        if let Some(b) = blocks {
            changes.push(Change {
                locale: target.into(),
                field: "blocks".into(),
                before: self.doc.get(target, "blocks"),
                after: b,
            });
        }
        if !labels.is_empty() {
            changes.push(Change {
                locale: target.into(),
                field: "labels".into(),
                before: self.doc.get(target, "labels"),
                after: Value::Array(labels),
            });
        }
        // A new translation gets a slug from its translated name/title.
        if let Some(title) = self.p.entity_type.title_field() {
            let current = self.doc.get(target, "slug");
            let empty = current
                .as_ref()
                .and_then(Value::as_str)
                .is_none_or(str::is_empty);
            let name = changes
                .iter()
                .find(|c| c.field == title)
                .and_then(|c| c.after.as_str())
                .map(|n| crate::feeds::slugify(n, 200));
            if empty && let Some(slug) = name.filter(|s| !s.is_empty()) {
                changes.push(Change {
                    locale: target.into(),
                    field: "slug".into(),
                    before: current,
                    after: json!(slug),
                });
            }
        }
        Ok((changes, warnings))
    }
}

/// One translatable text of the source.
#[derive(Debug, Clone, PartialEq)]
struct Unit {
    key: String,
    text: String,
    html: bool,
}

impl Unit {
    /// The text without markup (glossary terms are matched in text, not in HTML entities).
    fn plain(&self) -> String {
        if self.html {
            plain(&self.text, usize::MAX)
        } else {
            self.text.clone()
        }
    }
}

/// The texts of `locale` to translate, keyed by field (`blocks.3.html`, `labels.0.1`).
fn units(doc: &Doc, locale: &str) -> Vec<Unit> {
    let mut out = vec![];
    let mut push = |key: String, v: Option<&Value>, html: bool| {
        if let Some(s) = v.and_then(Value::as_str).filter(|s| !s.trim().is_empty()) {
            out.push(Unit {
                key,
                text: s.to_owned(),
                html,
            });
        }
    };
    for field in doc.entity_type().fields() {
        match *field {
            "slug" => {}
            "blocks" => {
                let blocks = doc.get(locale, "blocks").unwrap_or(Value::Null);
                for (i, b) in blocks.as_array().into_iter().flatten().enumerate() {
                    for k in ["text", "html", "alt", "caption", "label", "title"] {
                        push(format!("blocks.{i}.{k}"), b.get(k), k == "html");
                    }
                    for (j, item) in b["items"].as_array().into_iter().flatten().enumerate() {
                        push(
                            format!("blocks.{i}.items.{j}.question"),
                            item.get("question"),
                            false,
                        );
                        push(
                            format!("blocks.{i}.items.{j}.answer_html"),
                            item.get("answer_html"),
                            true,
                        );
                    }
                }
            }
            "labels" => {
                let labels = doc.get(locale, "labels").unwrap_or(Value::Null);
                for l in labels.as_array().into_iter().flatten() {
                    if let Some(path) = l["path"].as_str() {
                        push(format!("labels.{path}"), l.get("label"), false);
                    }
                }
            }
            f => push(
                f.to_owned(),
                doc.get(locale, f).as_ref(),
                f.ends_with("html"),
            ),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_html_keeps_structure_only() {
        let dirty = r#"<p onclick="x()">Hi <a href="https://evil.example/?q=secret">there</a><img src="https://evil.example/p.gif"><script>alert(1)</script></p><ul><li><strong>A</strong></li></ul><table><tr><td>t</td></tr></table>"#;
        let clean = sanitize_generated(dirty);
        assert_eq!(
            clean,
            "<p>Hi there</p><ul><li><strong>A</strong></li></ul>t"
        );
    }

    #[test]
    fn translated_html_keeps_only_source_urls() {
        let source = r#"<p>See <a href="https://shop.example/size">sizes</a></p>"#;
        let out = r#"<p>Pozri <a href="https://shop.example/size">veľkosti</a> a <a href="https://evil.example">toto</a><img src="https://evil.example/x.png"></p>"#;
        let clean = sanitize_translated(out, source);
        assert!(
            clean.contains(r#"href="https://shop.example/size""#),
            "{clean}"
        );
        assert!(!clean.contains("evil"), "{clean}");
    }

    #[test]
    fn proposal_requests_are_validated() {
        let ok = NewProposal {
            kind: ProposalKind::Translate,
            entity_type: EntityType::Menu,
            entity_id: "main".into(),
            locale: "cs".into(),
            target_locales: vec!["sk".into(), "en".into()],
            tone: Tone::default(),
            length: Length::default(),
        };
        assert!(ok.validate().is_ok());
        let code = |p: NewProposal| p.validate().unwrap_err().code();
        assert_eq!(
            code(NewProposal {
                target_locales: vec!["cs".into()],
                ..ok.clone()
            }),
            "invalid_locale"
        );
        assert_eq!(
            code(NewProposal {
                target_locales: vec!["sk".into(), "sk".into()],
                ..ok.clone()
            }),
            "invalid_locale"
        );
        assert_eq!(
            code(NewProposal {
                kind: ProposalKind::Seo,
                ..ok.clone()
            }),
            "invalid_proposal"
        );
        assert_eq!(
            code(NewProposal {
                kind: ProposalKind::ProductDescription,
                entity_type: EntityType::Category,
                target_locales: vec![],
                ..ok.clone()
            }),
            "invalid_proposal"
        );
        let unknown: Result<NewProposal, _> = serde_json::from_value(json!({
            "kind": "delete_everything", "entity_type": "product", "entity_id": "x", "locale": "cs"
        }));
        assert!(unknown.is_err());
    }

    #[test]
    fn page_blocks_and_menu_labels_become_units() {
        use crate::content::menus::{MenuEntry, MenuLink};
        let menu = Doc::Menu {
            handle: "main".into(),
            items: vec![MenuEntry {
                label_i18n: BTreeMap::from([("cs".into(), "Akce".into())]),
                link: MenuLink::Url {
                    url: "/akce".into(),
                },
                children: vec![MenuEntry {
                    label_i18n: BTreeMap::from([("cs".into(), "Léto".into())]),
                    link: MenuLink::Url {
                        url: "/leto".into(),
                    },
                    children: vec![],
                }],
            }],
        };
        let keys: Vec<String> = units(&menu, "cs").into_iter().map(|u| u.key).collect();
        assert_eq!(keys, vec!["labels.0", "labels.0.0"]);
        assert!(units(&menu, "sk").is_empty());
    }
}
