import cloudflare from "@astrojs/cloudflare";
import solid from "@astrojs/solid-js";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "astro/config";

// Platform-owned checkout app (spec §9.4, A1): one artifact for all tenants, served by the edge
// on `checkout.<shop-host>` with the CHECKOUT binding. Styled by the tenant's tokens
// (`/_p/tokens.css`, generated by the edge from theme.tokens.json).
export default defineConfig({
  output: "server",
  adapter: cloudflare({ imageService: "passthrough" }),
  session: false,
  integrations: [solid()],
  build: { inlineStylesheets: "never" },
  prefetch: false,
  vite: { plugins: [tailwindcss()] },
});
