/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/storefront/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The cart with totals and VAT recomputed now (shop or checkout capability). */
        get: operations["get_cart"];
        put?: never;
        /**
         * Creates an empty cart; the capability comes back in `X-Cart-Token` (the edge stores it in
         *     the HttpOnly `cart` cookie).
         */
        post: operations["create_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/cart/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Applies a coupon (one per cart; replaces an earlier one). `422` with the coupon's reason
         *     (`coupon_not_found`, `coupon_min_subtotal`, ...) when it does not apply.
         */
        post: operations["apply_coupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/cart/coupons/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_coupon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/cart/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts the checkout handoff (A1): revokes the shop capability (the edge clears the `cart`
         *     cookie) and returns a single-use handoff token.
         */
        post: operations["start_handoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/cart/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/cart/lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_line"];
        options?: never;
        head?: never;
        /** Sets the quantity (0 removes the line). */
        patch: operations["update_line"];
        trace?: never;
    };
    "/storefront/v1/checkout/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeems a handoff token on the checkout origin (A1): consumed atomically; returns a new
         *     checkout-scoped capability. `400 invalid_handoff` when unknown, used, expired or minted for
         *     another market.
         */
        post: operations["redeem_handoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current choice: cookie purposes from the anonymous subject (this browser), email
         *     purposes from the signed-in customer (checkout origin). `text_version: null` means no choice
         *     yet.
         */
        get: operations["get_consent"];
        put?: never;
        /**
         * Records a choice for the anonymous subject (minted on the first choice) and, when signed in
         *     on the checkout origin, for the customer. Answers the anonymous subject's new state.
         */
        post: operations["post_consent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_addresses"];
        put?: never;
        post: operations["add_address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/addresses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_address"];
        post?: never;
        delete: operations["delete_address"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["request_magic_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/magic-link/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["consume_magic_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/customer/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets or changes the password (A5). Every other session is signed out; a notice is emailed. */
        post: operations["set_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Events beacon (`/_p/e`). ponytail: accepted and dropped until WP14 stores consented events
         *     and server counters (A20).
         */
        post: operations["events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `robots.txt`, `llms.txt`, `sitemap.xml` (index) or `sitemap-<n>.xml` (chunk). */
        get: operations["file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/newsletter/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Newsletter sign-up. ponytail: validates and accepts; storage and the double opt-in mail
         *     arrive with the newsletter module (M2).
         */
        post: operations["newsletter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/pages/category/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A category listing with facets, sort options and pagination. Filtered or re-sorted URLs
         *     are `noindex,follow` with a canonical to the category (spec §9.5).
         */
        get: operations["category"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/pages/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/pages/product/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/pages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search results (name search until WP7's Meilisearch); always `noindex`. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/redirects/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The redirect for a path the theme could not render (the edge asks on 404, spec §9.5). */
        get: operations["resolve_redirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product search with variant-correct facets (spec §11.1, A23).
         * @description Results are distinct products; `variant_id` is the variant that matched best. Facets list
         *     every value found for the query and category; `available: false` values would match
         *     nothing with the other active filters and are shown disabled. No counts (A23).
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Typeahead: up to 8 suggestions, matching categories (≤ 3) first, then products. */
        get: operations["suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/v1/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Layout data: shop name, locale, markets, menus, consent config, messages, theme tokens. */
        get: operations["shop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            city: string;
            company?: string | null;
            /** @description ISO 3166-1 alpha-2 (`CZ`). */
            country: string;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            name: string;
            phone?: string | null;
            postal_code: string;
            street: string;
        };
        AddressInput: {
            city: string;
            company?: string | null;
            country: string;
            is_default?: boolean;
            name: string;
            phone?: string | null;
            postal_code: string;
            street: string;
        };
        AddressList: {
            items: components["schemas"]["Address"][];
        };
        Alternate: {
            href: string;
            /** @description hreflang value (`cs-CZ`, `x-default`). */
            locale: string;
        };
        AssetVariant: {
            /** Format: int64 */
            bytes: number;
            /** @description `avif`, `webp`, `jpeg` or `png`. */
            format: string;
            /** Format: int32 */
            height: number;
            /** @description Public-bucket key. */
            key: string;
            /** Format: int32 */
            width: number;
        };
        /** @enum {string} */
        Badge: "sale" | "new";
        /** @description Cache hints the edge reads from every page model (spec §8.2, A2). */
        CacheHints: {
            /**
             * Format: int32
             * @description Seconds.
             */
            max_age: number;
            public: boolean;
            /** @description Purge tags (`product:<id>`, `category:<id>`, `shop`, ...). */
            tags: string[];
        };
        CartCoupon: {
            /** @description Whether it applies to the cart right now. */
            applied: boolean;
            code: string;
            /** @description Why not (`coupon_min_subtotal`, `coupon_not_active`, ...). */
            reason?: string | null;
        };
        CartLineView: {
            /**
             * @description False when the variant is no longer sold (not priced, archived or sold out); such
             *     lines are not part of the totals.
             */
            available: boolean;
            /** @description This line's share of the coupon. */
            discount: components["schemas"]["MoneyView"];
            /** Format: uuid */
            id: string;
            image?: components["schemas"]["Image"] | null;
            /** Format: uuid */
            product_id: string;
            product_name: string;
            /** Format: int32 */
            quantity: number;
            sku: string;
            /** @description Product page slug (`/p/<slug>`). */
            slug: string;
            stock: components["schemas"]["StockState"];
            /** @description VAT rate in percent (`"21"`). */
            tax_rate: string;
            /** @description What the customer pays for the line (VAT included, after the coupon). */
            total: components["schemas"]["MoneyView"];
            unit_price: components["schemas"]["MoneyView"];
            /** Format: uuid */
            variant_id: string;
            /** @description Option values, e.g. `Zelená / M`. */
            variant_label: string;
        };
        CartView: {
            coupon?: components["schemas"]["CartCoupon"] | null;
            currency: components["schemas"]["Currency"];
            discount: components["schemas"]["MoneyView"];
            free_shipping_remaining?: components["schemas"]["MoneyView"] | null;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            item_count: number;
            lines: components["schemas"]["CartLineView"][];
            /** @description Country whose VAT applies (checkout sets it; the market's first country until then). */
            ship_to_country: string;
            /** @description Goods before the coupon. */
            subtotal: components["schemas"]["MoneyView"];
            /** @description Goods after the coupon, VAT included (shipping and payment arrive with checkout). */
            total: components["schemas"]["MoneyView"];
            vat: components["schemas"]["VatRow"][];
            vat_total: components["schemas"]["MoneyView"];
            /**
             * Format: int32
             * @description Changes with every modification.
             */
            version: number;
        };
        CategorySuggestion: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        CategoryTile: {
            href: string;
            image?: components["schemas"]["Image"] | null;
            label: string;
        };
        CategoryView: {
            description_html: string;
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        CheckoutCart: {
            /** @description Checkout-scoped cart capability (the edge sets it as the `__Host-cart` cookie). */
            cart_token: string;
        };
        /** @description A choice as posted to `/_p/consent` (the contract in `docs/decisions/consent-contract.md`). */
        ConsentChoice: {
            purposes: components["schemas"]["Purposes"];
            /** @description `banner` (default) or `preferences`. */
            source?: components["schemas"]["Source"];
            /** @description The consent text version the person saw (`GET /shop` → `consent.text_version`). */
            text_version: string;
        };
        ConsentConfig: {
            policy_url: string;
            /** @description The preferences page on the checkout origin. */
            preferences_url: string;
            /** @description Purposes the banner asks for (A20). */
            purposes: components["schemas"]["ConsentPurpose"][];
            /** @description Version of the consent texts; post it back with the choice (`POST /_p/consent`). */
            text_version: string;
        };
        /** @enum {string} */
        ConsentPurpose: "analytics" | "ads" | "personalization" | "email_marketing" | "review_invites";
        /** @description Current consent of a subject. */
        ConsentState: {
            purposes: components["schemas"]["Purposes"];
            /** @description Text version of the latest choice; `None` = no choice yet (show the banner). */
            text_version?: string | null;
        };
        CouponCode: {
            code: string;
        };
        /**
         * @description Currencies used by EU markets: the euro and the member states' own currencies.
         *     `BGN` is historic (Bulgaria adopted the euro on 2026-01-01) and kept for old documents.
         * @enum {string}
         */
        Currency: "BGN" | "CZK" | "DKK" | "EUR" | "HUF" | "PLN" | "RON" | "SEK";
        CustomerView: {
            email: string;
            email_verified: boolean;
            has_password: boolean;
            /** Format: uuid */
            id: string;
            locale: string;
            name?: string | null;
            phone?: string | null;
            /**
             * @description A password can be set without the current one right now (A5: signed in with an email
             *     link within the last 10 minutes).
             */
            recently_verified: boolean;
        };
        DeliveryEstimate: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        Facet: {
            /** @description `opt.<code>`, `param.<key>` or `brand`; the filter key to send back. */
            key: string;
            label: string;
            values: components["schemas"]["FacetValue"][];
        };
        /** @enum {string} */
        FacetKind: "option" | "parameter" | "brand";
        FacetValue: {
            /** @description Selecting it would still match something. Unavailable values are shown disabled (A23). */
            available: boolean;
            label: string;
            selected: boolean;
            value: string;
        };
        FacetValueView: {
            /** @description Selecting it would give no result (counts are not shown, A23). */
            disabled: boolean;
            /** @description The listing URL with this value toggled. */
            href: string;
            label: string;
            selected: boolean;
            value: string;
        };
        FacetView: {
            /** @description Query parameter name. */
            key: string;
            kind: components["schemas"]["FacetKind"];
            label: string;
            values: components["schemas"]["FacetValueView"][];
        };
        GpsrPartyView: {
            address: string;
            email?: string | null;
            name: string;
            phone?: string | null;
            url?: string | null;
        };
        /** @description General Product Safety Regulation information (Regulation (EU) 2023/988, art. 19). */
        GpsrView: {
            eu_responsible_person?: components["schemas"]["GpsrPartyView"] | null;
            manufacturer?: components["schemas"]["GpsrPartyView"] | null;
            safety_info?: string | null;
            warnings?: string | null;
        };
        HandoffToken: {
            /** @description Single use, valid for 60 seconds, for `checkout.<shop>/start?h=`. */
            token: string;
        };
        Hero: {
            cta: components["schemas"]["Link"];
            image?: components["schemas"]["Image"] | null;
            subtitle: string;
            title: string;
        };
        HomePage: {
            cache: components["schemas"]["CacheHints"];
            categories: components["schemas"]["CategoryTile"][];
            featured: components["schemas"]["ProductCard"][];
            /** @description Placeholder built from the catalog until CMS blocks exist (WP13). */
            hero: components["schemas"]["Hero"];
            seo: components["schemas"]["Seo"];
        };
        /**
         * @description An image with every generated width. Render `srcset` (AVIF) with a `sizes` that matches the
         *     real slot; `src` is a JPEG/PNG fallback. `width`/`height` are the intrinsic size of the
         *     largest variant (use them for the aspect ratio: no layout shift).
         */
        Image: {
            alt: string;
            /** Format: int32 */
            height: number;
            /** @description Fallback (JPEG or PNG) around 640 px wide. */
            src: string;
            /** @description AVIF candidates: `"/media/... 320w, /media/... 640w"`. */
            srcset: string;
            /** @description Fallback-format candidates. */
            srcset_fallback: string;
            /** @description WebP candidates, for `<picture>` fallbacks. */
            srcset_webp: string;
            /** Format: int32 */
            width: number;
        };
        LineUpdate: {
            /**
             * Format: int32
             * @description 0 removes the line.
             */
            quantity: number;
        };
        Link: {
            href: string;
            label: string;
        };
        /** @description A category page or search results. */
        ListingPage: {
            breadcrumbs: components["schemas"]["Link"][];
            cache: components["schemas"]["CacheHints"];
            category?: components["schemas"]["CategoryView"] | null;
            facets: components["schemas"]["FacetView"][];
            pagination: components["schemas"]["Pagination"];
            products: components["schemas"]["ProductCard"][];
            /** @description The search query (absent on category pages). */
            query?: string | null;
            seo: components["schemas"]["Seo"];
            sort: components["schemas"]["SortOption"][];
            subcategories: components["schemas"]["Link"][];
            title: string;
            /** Format: int32 */
            total: number;
        };
        MagicLinkRequest: {
            email: string;
            /** @description Relative path on the checkout origin to land on after sign-in (default `/account`). */
            redirect?: string | null;
        };
        MagicLinkToken: {
            token: string;
        };
        MarketLink: {
            code: string;
            currency: string;
            current: boolean;
            /** @description Home page of the market. */
            href: string;
            /** @description hreflang value (`sk-SK`). */
            locale: string;
            name: string;
        };
        MenuItem: {
            children: components["schemas"]["Link"][];
            href: string;
            label: string;
        };
        Menus: {
            footer: components["schemas"]["MenuItem"][];
            main: components["schemas"]["MenuItem"][];
        };
        /** @description The API shape of an amount (spec §8.1): `{amount_minor, currency, formatted}`. */
        MoneyView: {
            /** Format: int64 */
            amount_minor: number;
            currency: components["schemas"]["Currency"];
            /** @example 1 290,00 Kč */
            formatted: string;
        };
        NewLine: {
            /**
             * Format: int32
             * @description 1-999 (added to an existing line of the same variant).
             */
            quantity?: number;
            /** Format: uuid */
            variant_id: string;
        };
        NewsletterSignup: {
            email: string;
        };
        NewsletterStatus: {
            /** @description `accepted`: double opt-in mail arrives with the newsletter module (M2, §11.5). */
            status: string;
        };
        OptionValueView: {
            code: string;
            name: string;
        };
        OptionView: {
            code: string;
            name: string;
            values: components["schemas"]["OptionValueView"][];
        };
        Pagination: {
            next?: string | null;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pages: number;
            prev?: string | null;
        };
        ParameterView: {
            key: string;
            name: string;
            value: string;
        };
        PasswordChange: {
            /** @description Required unless the session signed in with an email link within the last 10 minutes. */
            current_password?: string | null;
            new_password: string;
        };
        PasswordLogin: {
            email: string;
            password: string;
            redirect?: string | null;
        };
        PriceRange: {
            /** Format: int64 */
            max_minor: number;
            /** Format: int64 */
            min_minor: number;
        };
        /**
         * @description A selling price with its Omnibus reference (A18). `reference_price` and
         *     `discount_percent` are present only when a reduction may be claimed; they are computed
         *     against the lowest price of the 30 days before the reduction, never `compare_at`.
         */
        PriceView: {
            /** Format: int32 */
            discount_percent?: number | null;
            price: components["schemas"]["MoneyView"];
            reference_price?: components["schemas"]["MoneyView"] | null;
            unit_price?: components["schemas"]["UnitPrice"] | null;
        };
        /** @description RFC 9457 problem details body. */
        Problem: {
            /** @description Stable machine-readable error code, e.g. `not_found`. */
            code: string;
            detail?: string | null;
            /** Format: int32 */
            status: number;
            title: string;
            /** @description Always `about:blank`; `code` carries the specific error kind. */
            type: string;
        };
        ProductCard: components["schemas"]["PriceView"] & {
            badges: components["schemas"]["Badge"][];
            brand?: string | null;
            /** Format: uuid */
            id: string;
            /** @description Up to two images: the main one and a second (hover) image. */
            images: components["schemas"]["Image"][];
            name: string;
            /** @description Variants differ in price: show the price as "from". */
            price_varies: boolean;
            slug: string;
            /** @description The best state over the product's variants. */
            stock: components["schemas"]["StockState"];
        };
        ProductDetail: {
            brand?: string | null;
            /** @description Sanitized server-side; the only HTML a theme may render unescaped. */
            description_html: string;
            gpsr?: components["schemas"]["GpsrView"] | null;
            /** Format: uuid */
            id: string;
            images: components["schemas"]["Image"][];
            name: string;
            options: components["schemas"]["OptionView"][];
            parameters: components["schemas"]["ParameterView"][];
            short_description: string;
            slug: string;
            /** @description Variants sold in this market, in the merchant's order. */
            variants: components["schemas"]["VariantView"][];
        };
        ProductPage: {
            breadcrumbs: components["schemas"]["Link"][];
            cache: components["schemas"]["CacheHints"];
            delivery_estimate?: components["schemas"]["DeliveryEstimate"] | null;
            product: components["schemas"]["ProductDetail"];
            seo: components["schemas"]["Seo"];
        };
        /** @description Per-purpose choices: `None` = not asked (or not part of this choice). */
        Purposes: {
            ads?: boolean | null;
            analytics?: boolean | null;
            email_marketing?: boolean | null;
            personalization?: boolean | null;
            review_invites?: boolean | null;
        };
        Recommendations: {
            cache: components["schemas"]["CacheHints"];
            products: components["schemas"]["ProductCard"][];
        };
        /** @description What the edge needs to answer a redirect. */
        ResolvedRedirect: {
            /** Format: int32 */
            code: number;
            to_path: string;
        };
        SearchHit: {
            brand?: string | null;
            /** @description The first product image, in the list-sized variants (up to 640 px). */
            image: components["schemas"]["AssetVariant"][];
            /** @description At least one variant can be bought now. */
            in_stock: boolean;
            name: string;
            /** @description Current price of the matched variant in the market (gross). */
            price: components["schemas"]["MoneyView"];
            /** Format: uuid */
            product_id: string;
            slug: string;
            /**
             * Format: uuid
             * @description The variant that matched best (e.g. the red one when filtering by red).
             */
            variant_id: string;
        };
        SearchResult: {
            facets: components["schemas"]["Facet"][];
            items: components["schemas"]["SearchHit"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            per_page: number;
            price_range?: components["schemas"]["PriceRange"] | null;
            /**
             * Format: int64
             * @description Matching products (before rehydration dropped any that just became unavailable).
             */
            total: number;
            /** Format: int32 */
            total_pages: number;
        };
        Seo: {
            alternates: components["schemas"]["Alternate"][];
            canonical: string;
            description: string;
            /** @description JSON-LD documents for `<script type="application/ld+json">`. */
            json_ld: unknown[];
            /** @description `noindex,follow` on filtered listings (spec §9.5); absent otherwise. */
            robots?: string | null;
            title: string;
        };
        ShopModel: {
            cache: components["schemas"]["CacheHints"];
            consent: components["schemas"]["ConsentConfig"];
            currencies: string[];
            currency: string;
            free_shipping_threshold?: components["schemas"]["MoneyView"] | null;
            /** @description Placeholders until CMS pages exist (WP13). */
            legal_pages: components["schemas"]["Link"][];
            /** @description Active locale (`cs`); also the `lang` of pages. */
            locale: string;
            /** @description Locales of this market (M1: the market's default locale; prefixes arrive with WP8). */
            locales: components["schemas"]["Alternate"][];
            /** @description The tenant's markets (other shops of the same merchant). */
            markets: components["schemas"]["MarketLink"][];
            menus: components["schemas"]["Menus"];
            /** @description Platform UI messages in the active locale (`cart.add` -> "Přidat do košíku"). */
            messages: {
                [key: string]: string;
            };
            name: string;
            seo: components["schemas"]["Seo"];
            /** @description Design tokens of the active theme (A6). */
            tokens?: unknown;
            tracking: components["schemas"]["Tracking"];
            trust: components["schemas"]["Trust"];
        };
        SignInResult: {
            customer: components["schemas"]["CustomerView"];
            /** @description Relative path on the checkout origin to continue to. */
            redirect: string;
        };
        /** @enum {string} */
        Sort: "recommended" | "price_asc" | "price_desc" | "newest";
        SortOption: {
            href: string;
            label: string;
            selected: boolean;
            value: components["schemas"]["Sort"];
        };
        /**
         * @description Where a choice was made.
         * @enum {string}
         */
        Source: "banner" | "preferences" | "checkout" | "linked";
        /** @enum {string} */
        StockState: "in_stock" | "low_stock" | "backorder" | "out_of_stock";
        Suggestions: {
            categories: components["schemas"]["CategorySuggestion"][];
            products: components["schemas"]["SearchHit"][];
        };
        Tracking: {
            /**
             * Format: double
             * @description Share of consented page views that report Web Vitals (spec §9.6).
             */
            rum_sample_rate: number;
        };
        Trust: {
            delivery: string;
            payments: string[];
            returns: string;
        };
        /** @description Price per unit of measure (EU price indication directive), e.g. per 1 kg. */
        UnitPrice: {
            price: components["schemas"]["MoneyView"];
            /** @description `kg`, `l`, `m`, `m²` or `ks`. */
            unit: string;
        };
        VariantView: components["schemas"]["PriceView"] & {
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description Index into `product.images` of this variant's first image.
             */
            image_index?: number | null;
            is_default: boolean;
            /** @description Option code -> value code (`{"color": "red", "size": "m"}`). */
            options: {
                [key: string]: string;
            };
            sku: string;
            stock: components["schemas"]["StockState"];
        };
        VatRow: {
            gross: components["schemas"]["MoneyView"];
            net: components["schemas"]["MoneyView"];
            /** @description Percent (`"21"`). */
            rate: string;
            vat: components["schemas"]["MoneyView"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_cart: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_cart: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    /** @description Shop cart capability */
                    "X-Cart-Token"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
        };
    };
    apply_coupon: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    remove_coupon: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
        };
    };
    start_handoff: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffToken"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description cart_empty */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    add_line: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewLine"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description out_of_stock / insufficient_stock */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    remove_line: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
        };
    };
    update_line: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Cart capability from the `cart` cookie (shop) or `__Host-cart` (checkout origin). */
                "X-Cart-Token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartView"];
                };
            };
        };
    };
    redeem_handoff: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutCart"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_consent: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Anonymous subject id from the consent cookie (32 hex characters). */
                "X-Consent-Subject"?: string | null;
                /** @description Checkout origin only: the signed-in customer's session. */
                "X-Customer-Session"?: string | null;
                /** @description The client's IP (stored as a salted hash with the record). */
                "X-Client-Ip"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentState"];
                };
            };
        };
    };
    post_consent: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Anonymous subject id from the consent cookie (32 hex characters). */
                "X-Consent-Subject"?: string | null;
                /** @description Checkout origin only: the signed-in customer's session. */
                "X-Customer-Session"?: string | null;
                /** @description The client's IP (stored as a salted hash with the record). */
                "X-Client-Ip"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentChoice"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description The anonymous subject id (for the edge's cookie) */
                    "X-Consent-Subject"?: string;
                    /** @description `<text_version>.<mask>` for the script-readable cookie */
                    "X-Consent-Summary"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentState"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_addresses: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressList"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    add_address: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_address: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_address: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Checkout cart capability (`__Host-cart`): the cart is attached to the customer (A4). */
                "X-Cart-Token"?: string | null;
                /** @description Anonymous consent subject (consent cookie): its choices move to the customer (A20). */
                "X-Consent-Subject"?: string | null;
                /** @description The client's IP (rate limits; stored only as a salted hash). */
                "X-Client-Ip"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description New session (for the edge only) */
                    "X-Session-Token"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            /** @description invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description too_many_attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    /** @description The edge deletes the cookie */
                    "X-Session-Clear"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_magic_link: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Checkout cart capability (`__Host-cart`): the cart is attached to the customer (A4). */
                "X-Cart-Token"?: string | null;
                /** @description Anonymous consent subject (consent cookie): its choices move to the customer (A20). */
                "X-Consent-Subject"?: string | null;
                /** @description The client's IP (rate limits; stored only as a salted hash). */
                "X-Client-Ip"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Sent if the address can receive mail (same answer for every address) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description too_many_attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    consume_magic_link: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Checkout cart capability (`__Host-cart`): the cart is attached to the customer (A4). */
                "X-Cart-Token"?: string | null;
                /** @description Anonymous consent subject (consent cookie): its choices move to the customer (A20). */
                "X-Consent-Subject"?: string | null;
                /** @description The client's IP (rate limits; stored only as a salted hash). */
                "X-Client-Ip"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description New session (for the edge only) */
                    "X-Session-Token"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            /** @description invalid_magic_link */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerView"];
                };
            };
            /** @description not_signed_in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    set_password: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
                /** @description Session token from the checkout origin's `__Host-sid` cookie (set by the edge). */
                "X-Customer-Session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_signed_in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description reauth_required | invalid_current_password */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description weak_password */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description too_many_attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path: {
                /** @description robots.txt, llms.txt, sitemap.xml, sitemap-<n>.xml */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    newsletter: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsletterSignup"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsletterStatus"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    category: {
        parameters: {
            query?: {
                /** @description `recommended` (default), `price_asc`, `price_desc`, `newest`, `name`. */
                sort?: string;
                /** @description 1-based page (24 products per page). */
                page?: number;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomePage"];
                };
            };
        };
    };
    product_page: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                sort?: string;
                page?: number;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
        };
    };
    recommendations: {
        parameters: {
            query?: {
                /** @description `product:<id>`, `cart` or `home`. */
                context?: string;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
        };
    };
    resolve_redirect: {
        parameters: {
            query: {
                /** @description Requested path (`/stary-produkt`); the query string is ignored. */
                path: string;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedRedirect"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Search text (≤ 200 characters). Empty: browse (e.g. a category listing). */
                q?: string;
                sort?: "relevance" | "price_asc" | "price_desc" | "newest";
                /** @description 1-based page (results beyond the first 1000 are not available). */
                page?: number;
                /** @description 1-48, default 24. */
                per_page?: number;
                /** @description Only products in this category or its subcategories. */
                category?: string;
                /** @description Only variants that can be bought now. */
                in_stock?: boolean;
                /** @description Gross price bounds in minor units (inclusive). */
                price_min?: number;
                price_max?: number;
                /**
                 * @description Facet filters: `f.<facet key>=<value>`, repeatable (`f.opt.color=red&f.opt.color=blue`).
                 *     Keys are the `facets[].key` of a previous response. Values of one facet are OR-ed,
                 *     facets are AND-ed, and all of them must hold for one variant.
                 */
                "f.{facet}"?: string;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Search is temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    suggest: {
        parameters: {
            query: {
                /** @description What the shopper typed so far (≤ 200 characters). */
                q: string;
            };
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestions"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Search is temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    shop: {
        parameters: {
            query?: never;
            header: {
                /** @description The tenant's public storefront token. */
                "X-Storefront-Token": string;
                /** @description Market id resolved from the shop host by the edge. */
                "X-Market": string;
                /** @description Locale hint (one of the market's locales). */
                "X-Locale"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopModel"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
